# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dejavu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dejavu
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'dejavuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dejavuUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
